name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: macOS stuff
      if: runner.os == 'macOS'
      # - install pkg-config (we cannot use `pkgconf` tool because of cross-compilaton - vcpkg
      #   builds it for ARM, while it should be the runner's architecture (x86-64))
      run: brew install pkg-config

    # vcpkg
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/pylibrb_vcpkg'

    - uses: pypa/cibuildwheel@v2.16.2

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl

  upload_all:
    name: Upload to PyPI
    needs: [build_wheels, build_sdist]
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # mandatory for trusted publishing on PyPI

    steps:
    - uses: actions/setup-python@v4
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - name: Publish package distributions to PyPI 
      uses: pypa/gh-action-pypi-publish@release/v1
