name: tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    env:
      PYLIBRB_VCPKG_ROOT: ${{ github.workspace }}/pylibrb_vcpkg

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    # vcpkg
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ env.PYLIBRB_VCPKG_ROOT }}'

    - name: Build
      run: pip install --verbose .
      env:
        CMAKE_TOOLCHAIN_FILE: ${{ env.PYLIBRB_VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

    - name: Test
      run: |
        python -m pip install -r ./tests/requirements.txt
        python -m pytest ./tests
